-- P64 Phase 3 — Assessments, Integrity, Completion Rules and Certificates
-- (master plan Phase 3 §F). Additive only; every default reproduces the
-- pre-Phase-3 behaviour; open attempts are untouched (backfilled
-- `started_at`, no deadline, so the sweep ignores them); no historical
-- certificate is auto-issued.
--
-- Sections:
--   1. Enum vocabularies and enum extensions.
--   2. Columns on quizzes / quiz_questions / quiz_attempts / assignments /
--      assignment_submissions / courses / course_progress.
--   3. New tables: quiz_attempt_events, quiz_results,
--      quiz_student_overrides, certificate_templates, certificates,
--      certificate_serial_counters.
--   4. Backfill (started_at = created_at).
--   5. SECURITY DEFINER helpers (attempt → course/quiz/student lookups
--      that RLS policies and the deadline sweep need; serial allocation;
--      public verification projection).
--   6. RLS — every new table FORCE RLS; self / review / tenant / platform
--      tiers; retention DELETE tier on events; review UPDATE on attempts;
--      tenant UPDATE on course_progress for certificate issuance.

-- ---------------------------------------------------------------------
-- 1–3. DDL (generated by `prisma migrate diff`, unrelated drift removed)
-- ---------------------------------------------------------------------
CREATE TYPE "quiz_mode" AS ENUM ('practice', 'exam');
CREATE TYPE "quiz_layout" AS ENUM ('all_questions', 'one_per_page');
CREATE TYPE "quiz_grading_policy" AS ENUM ('highest', 'latest', 'first', 'average');
CREATE TYPE "quiz_disclosure" AS ENUM ('immediately', 'after_due', 'after_attempts_exhausted', 'never');
CREATE TYPE "quiz_integrity_mode" AS ENUM ('off', 'monitor', 'warn', 'strict');
CREATE TYPE "assessment_late_policy" AS ENUM ('block', 'accept_flagged');
CREATE TYPE "attempt_grading_status" AS ENUM ('not_required', 'pending', 'graded');
CREATE TYPE "quiz_attempt_event_type" AS ENUM ('visibility_hidden', 'visibility_visible', 'blur', 'focus', 'fullscreen_exit', 'fullscreen_enter', 'copy', 'paste', 'cut', 'contextmenu', 'print', 'heartbeat', 'second_session', 'device_change', 'warning_acknowledged');
CREATE TYPE "certificate_state" AS ENUM ('issued', 'revoked');
CREATE TYPE "certificate_render_status" AS ENUM ('pending', 'ready', 'failed');
ALTER TYPE "certificate_status" ADD VALUE 'issued';
ALTER TYPE "certificate_status" ADD VALUE 'revoked';
ALTER TYPE "quiz_attempt_status" ADD VALUE 'expired';
ALTER TYPE "quiz_attempt_status" ADD VALUE 'invalidated';
ALTER TYPE "quiz_question_type" ADD VALUE 'short_answer';
ALTER TYPE "quiz_question_type" ADD VALUE 'essay';
ALTER TABLE "assignment_submissions" ADD COLUMN     "attachment_asset_id" TEXT,
ADD COLUMN     "draft_response" TEXT,
ADD COLUMN     "draft_saved_at" TIMESTAMP(3),
ADD COLUMN     "is_late" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "submitted_revision" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "assignments" ADD COLUMN     "late_policy" "assessment_late_policy" NOT NULL DEFAULT 'accept_flagged',
ADD COLUMN     "required_for_completion" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "course_progress" ADD COLUMN     "completed_at" TIMESTAMP(3),
ADD COLUMN     "overall_score" DECIMAL(5,2);
ALTER TABLE "courses" ADD COLUMN     "certificate_min_score" INTEGER,
ADD COLUMN     "certificate_template_id" TEXT,
ADD COLUMN     "certificates_enabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "completion_rule" JSONB NOT NULL DEFAULT '{"lessons":"all","requiredQuizzes":true,"requiredAssignments":true,"minOverallScore":null}';
ALTER TABLE "quiz_attempts" ADD COLUMN     "answers_revision" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "auto_submitted" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "auto_submitted_reason" TEXT,
ADD COLUMN     "deadline_at" TIMESTAMP(3),
ADD COLUMN     "graded_at" TIMESTAMP(3),
ADD COLUMN     "graded_by" TEXT,
ADD COLUMN     "grading_status" "attempt_grading_status" NOT NULL DEFAULT 'not_required',
ADD COLUMN     "integrity_flagged" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "invalidated_at" TIMESTAMP(3),
ADD COLUMN     "invalidated_by" TEXT,
ADD COLUMN     "invalidation_reason" TEXT,
ADD COLUMN     "is_late" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "last_saved_at" TIMESTAMP(3),
ADD COLUMN     "manual_grades" JSONB,
ADD COLUMN     "points_earned" DECIMAL(8,2),
ADD COLUMN     "points_total" DECIMAL(8,2),
ADD COLUMN     "question_ids" JSONB,
ADD COLUMN     "seed" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "settings_snapshot" JSONB,
ADD COLUMN     "started_at" TIMESTAMP(3),
ADD COLUMN     "violation_count" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "quiz_questions" ADD COLUMN     "accepted_answers" JSONB,
ADD COLUMN     "explanation" TEXT,
ADD COLUMN     "points" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "related_lesson_id" TEXT;
ALTER TABLE "quizzes" ADD COLUMN     "available_from" TIMESTAMP(3),
ADD COLUMN     "available_until" TIMESTAMP(3),
ADD COLUMN     "due_at" TIMESTAMP(3),
ADD COLUMN     "grading_policy" "quiz_grading_policy" NOT NULL DEFAULT 'highest',
ADD COLUMN     "hide_timer" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "integrity_mode" "quiz_integrity_mode" NOT NULL DEFAULT 'off',
ADD COLUMN     "late_policy" "assessment_late_policy" NOT NULL DEFAULT 'accept_flagged',
ADD COLUMN     "layout" "quiz_layout" NOT NULL DEFAULT 'all_questions',
ADD COLUMN     "max_violations" INTEGER NOT NULL DEFAULT 3,
ADD COLUMN     "mode" "quiz_mode" NOT NULL DEFAULT 'practice',
ADD COLUMN     "questions_per_attempt" INTEGER,
ADD COLUMN     "require_fullscreen" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "required_for_completion" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "required_to_progress" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "show_answers" "quiz_disclosure" NOT NULL DEFAULT 'never',
ADD COLUMN     "show_explanations" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "show_score" "quiz_disclosure" NOT NULL DEFAULT 'immediately',
ADD COLUMN     "shuffle_options" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "shuffle_questions" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "time_limit_seconds" INTEGER;
CREATE TABLE "quiz_attempt_events" (
    "id" TEXT NOT NULL,
    "attempt_id" TEXT NOT NULL,
    "type" "quiz_attempt_event_type" NOT NULL,
    "counted" BOOLEAN NOT NULL DEFAULT false,
    "client_at" TIMESTAMP(3),
    "server_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "payload" JSONB,
    CONSTRAINT "quiz_attempt_events_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "quiz_results" (
    "id" TEXT NOT NULL,
    "quiz_id" TEXT NOT NULL,
    "student_id" TEXT NOT NULL,
    "attempts_count" INTEGER NOT NULL DEFAULT 0,
    "best_score" DECIMAL(5,2),
    "latest_score" DECIMAL(5,2),
    "effective_score" DECIMAL(5,2),
    "passed" BOOLEAN NOT NULL DEFAULT false,
    "effective_attempt_id" TEXT,
    "pending_grading" BOOLEAN NOT NULL DEFAULT false,
    "computed_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "quiz_results_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "quiz_student_overrides" (
    "id" TEXT NOT NULL,
    "quiz_id" TEXT NOT NULL,
    "student_id" TEXT NOT NULL,
    "time_multiplier" DECIMAL(4,2) NOT NULL DEFAULT 1,
    "extra_attempts" INTEGER NOT NULL DEFAULT 0,
    "available_from" TIMESTAMP(3),
    "available_until" TIMESTAMP(3),
    "reason" TEXT,
    "created_by" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "quiz_student_overrides_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "certificate_templates" (
    "id" TEXT NOT NULL,
    "academy_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "logo_url" TEXT,
    "signature_url" TEXT,
    "signatory_name" TEXT,
    "signatory_title" TEXT,
    "wording" JSONB NOT NULL DEFAULT '{}',
    "version" INTEGER NOT NULL DEFAULT 1,
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "certificate_templates_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "certificates" (
    "id" TEXT NOT NULL,
    "academy_id" TEXT NOT NULL,
    "course_id" TEXT NOT NULL,
    "enrollment_id" TEXT NOT NULL,
    "student_id" TEXT NOT NULL,
    "serial" TEXT NOT NULL,
    "verification_code" TEXT NOT NULL,
    "status" "certificate_state" NOT NULL DEFAULT 'issued',
    "snapshot" JSONB NOT NULL,
    "template_id" TEXT,
    "template_version" INTEGER NOT NULL DEFAULT 1,
    "version" INTEGER NOT NULL DEFAULT 1,
    "locale" TEXT NOT NULL DEFAULT 'en',
    "issued_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "issued_by" TEXT,
    "revoked_at" TIMESTAMP(3),
    "revoked_by" TEXT,
    "revoke_reason" TEXT,
    "render_status" "certificate_render_status" NOT NULL DEFAULT 'pending',
    "storage_key" TEXT,
    "rendered_at" TIMESTAMP(3),
    "render_error" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "certificates_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "certificate_serial_counters" (
    "academy_id" TEXT NOT NULL,
    "year" INTEGER NOT NULL,
    "next_value" INTEGER NOT NULL DEFAULT 1,
    CONSTRAINT "certificate_serial_counters_pkey" PRIMARY KEY ("academy_id","year")
);
CREATE INDEX "quiz_attempt_events_attempt_id_server_at_idx" ON "quiz_attempt_events"("attempt_id", "server_at");
CREATE INDEX "quiz_attempt_events_server_at_idx" ON "quiz_attempt_events"("server_at");
CREATE INDEX "quiz_results_student_id_idx" ON "quiz_results"("student_id");
CREATE UNIQUE INDEX "quiz_results_quiz_id_student_id_key" ON "quiz_results"("quiz_id", "student_id");
CREATE UNIQUE INDEX "quiz_student_overrides_quiz_id_student_id_key" ON "quiz_student_overrides"("quiz_id", "student_id");
CREATE INDEX "certificate_templates_academy_id_is_default_idx" ON "certificate_templates"("academy_id", "is_default");
CREATE UNIQUE INDEX "certificates_enrollment_id_key" ON "certificates"("enrollment_id");
CREATE UNIQUE INDEX "certificates_verification_code_key" ON "certificates"("verification_code");
CREATE INDEX "certificates_student_id_idx" ON "certificates"("student_id");
CREATE INDEX "certificates_academy_id_issued_at_idx" ON "certificates"("academy_id", "issued_at" DESC);
CREATE INDEX "certificates_course_id_idx" ON "certificates"("course_id");
CREATE UNIQUE INDEX "certificates_academy_id_serial_key" ON "certificates"("academy_id", "serial");
CREATE INDEX "quiz_attempts_status_deadline_at_idx" ON "quiz_attempts"("status", "deadline_at");
ALTER TABLE "courses" ADD CONSTRAINT "courses_certificate_template_id_fkey" FOREIGN KEY ("certificate_template_id") REFERENCES "certificate_templates"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "quiz_attempts" ADD CONSTRAINT "quiz_attempts_graded_by_fkey" FOREIGN KEY ("graded_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "quiz_attempts" ADD CONSTRAINT "quiz_attempts_invalidated_by_fkey" FOREIGN KEY ("invalidated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "assignment_submissions" ADD CONSTRAINT "assignment_submissions_attachment_asset_id_fkey" FOREIGN KEY ("attachment_asset_id") REFERENCES "media_assets"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "quiz_attempt_events" ADD CONSTRAINT "quiz_attempt_events_attempt_id_fkey" FOREIGN KEY ("attempt_id") REFERENCES "quiz_attempts"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "quiz_results" ADD CONSTRAINT "quiz_results_quiz_id_fkey" FOREIGN KEY ("quiz_id") REFERENCES "quizzes"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "quiz_results" ADD CONSTRAINT "quiz_results_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "quiz_student_overrides" ADD CONSTRAINT "quiz_student_overrides_quiz_id_fkey" FOREIGN KEY ("quiz_id") REFERENCES "quizzes"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "quiz_student_overrides" ADD CONSTRAINT "quiz_student_overrides_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "quiz_student_overrides" ADD CONSTRAINT "quiz_student_overrides_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "certificate_templates" ADD CONSTRAINT "certificate_templates_academy_id_fkey" FOREIGN KEY ("academy_id") REFERENCES "academies"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "certificates" ADD CONSTRAINT "certificates_academy_id_fkey" FOREIGN KEY ("academy_id") REFERENCES "academies"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "certificates" ADD CONSTRAINT "certificates_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "courses"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "certificates" ADD CONSTRAINT "certificates_enrollment_id_fkey" FOREIGN KEY ("enrollment_id") REFERENCES "enrollments"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "certificates" ADD CONSTRAINT "certificates_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "certificates" ADD CONSTRAINT "certificates_issued_by_fkey" FOREIGN KEY ("issued_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "certificates" ADD CONSTRAINT "certificates_revoked_by_fkey" FOREIGN KEY ("revoked_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "certificate_serial_counters" ADD CONSTRAINT "certificate_serial_counters_academy_id_fkey" FOREIGN KEY ("academy_id") REFERENCES "academies"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- ---------------------------------------------------------------------
-- 4. Backfill — existing attempts get a start time and no deadline.
-- ---------------------------------------------------------------------
UPDATE "quiz_attempts" SET "started_at" = "created_at" WHERE "started_at" IS NULL;

-- ---------------------------------------------------------------------
-- 5. SECURITY DEFINER helpers
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION quiz_course_id(p_quiz_id text)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT q."course_id" FROM "quizzes" q WHERE q."id" = p_quiz_id;
$$;

CREATE OR REPLACE FUNCTION quiz_attempt_quiz_id(p_attempt_id text)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT a."quiz_id" FROM "quiz_attempts" a WHERE a."id" = p_attempt_id;
$$;

CREATE OR REPLACE FUNCTION quiz_attempt_student_id(p_attempt_id text)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT a."student_id" FROM "quiz_attempts" a WHERE a."id" = p_attempt_id;
$$;

CREATE OR REPLACE FUNCTION quiz_attempt_course_id(p_attempt_id text)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT q."course_id"
  FROM "quiz_attempts" a
  JOIN "quizzes" q ON q."id" = a."quiz_id"
  WHERE a."id" = p_attempt_id;
$$;

-- The deadline sweep runs with no tenant or user context (it is the
-- system acting on its own behalf), so it cannot see `quiz_attempts`
-- through any policy. This definer returns only the ids the sweep needs;
-- each attempt is then finalised under ITS OWN student's context, so the
-- write path stays inside the self policies. Grace of 30 s matches
-- `QUIZ_SUBMIT_GRACE_SECONDS` in the engine.
CREATE OR REPLACE FUNCTION find_due_quiz_attempts(p_limit integer)
RETURNS TABLE ("id" text, "student_id" text, "deadline_at" timestamp(3))
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT a."id", a."student_id", a."deadline_at"
  FROM "quiz_attempts" a
  WHERE a."status" = 'in_progress'
    AND a."deadline_at" IS NOT NULL
    AND a."deadline_at" + interval '30 seconds' < now()
  ORDER BY a."deadline_at" ASC
  LIMIT LEAST(GREATEST(COALESCE(p_limit, 100), 1), 500);
$$;

-- Serial allocation is atomic (single UPSERT) and refuses to allocate for
-- an academy outside the caller's tenant context: the function is a
-- definer, so the check is what keeps it honest.
CREATE OR REPLACE FUNCTION next_certificate_serial(p_academy_id text, p_year integer)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_org text;
  v_value integer;
BEGIN
  SELECT a."organization_id" INTO v_org FROM "academies" a WHERE a."id" = p_academy_id;
  IF v_org IS NULL OR v_org <> current_setting('app.current_organization_id', true) THEN
    RAISE EXCEPTION 'certificate serial allocation refused for academy %', p_academy_id
      USING ERRCODE = 'insufficient_privilege';
  END IF;
  INSERT INTO "certificate_serial_counters" ("academy_id", "year", "next_value")
  VALUES (p_academy_id, p_year, 2)
  ON CONFLICT ("academy_id", "year")
  DO UPDATE SET "next_value" = "certificate_serial_counters"."next_value" + 1
  RETURNING "next_value" - 1 INTO v_value;
  RETURN v_value;
END;
$$;

-- Public verification: returns ONLY the fields the plan allows a stranger
-- to see (issued-to, course, academy, date, status) and never the
-- snapshot's score, email or instructors. Uniform shape for issued and
-- revoked; unknown codes return no row and the API pads its timing.
CREATE OR REPLACE FUNCTION verify_certificate(p_code text)
RETURNS TABLE (
  "serial" text,
  "status" "certificate_state",
  "issued_to" text,
  "course_title" text,
  "academy_name" text,
  "academy_slug" text,
  "academy_id" text,
  "issued_at" timestamp(3),
  "completed_at" text,
  "revoked_at" timestamp(3),
  "version" integer
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT
    c."serial",
    c."status",
    c."snapshot"->>'learnerName',
    c."snapshot"->>'courseTitle',
    c."snapshot"->>'academyName',
    a."slug",
    c."academy_id",
    c."issued_at",
    c."snapshot"->>'completedAt',
    c."revoked_at",
    c."version"
  FROM "certificates" c
  JOIN "academies" a ON a."id" = c."academy_id"
  WHERE c."verification_code" = upper(regexp_replace(p_code, '[^A-Za-z0-9]', '', 'g'))
  LIMIT 1;
$$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'atlas_app') THEN
    REVOKE ALL ON FUNCTION find_due_quiz_attempts(integer) FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION find_due_quiz_attempts(integer) TO "atlas_app";
    REVOKE ALL ON FUNCTION next_certificate_serial(text, integer) FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION next_certificate_serial(text, integer) TO "atlas_app";
    REVOKE ALL ON FUNCTION verify_certificate(text) FROM PUBLIC;
    GRANT EXECUTE ON FUNCTION verify_certificate(text) TO "atlas_app";
  END IF;
END $$;

-- ---------------------------------------------------------------------
-- 6. RLS
-- ---------------------------------------------------------------------

-- quiz_attempt_events ---------------------------------------------------
ALTER TABLE "quiz_attempt_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "quiz_attempt_events" FORCE ROW LEVEL SECURITY;

CREATE POLICY "quiz_attempt_events_self_select" ON "quiz_attempt_events"
  FOR SELECT
  USING (quiz_attempt_student_id("attempt_id") = current_setting('app.current_user_id', true));

CREATE POLICY "quiz_attempt_events_self_insert" ON "quiz_attempt_events"
  FOR INSERT
  WITH CHECK (quiz_attempt_student_id("attempt_id") = current_setting('app.current_user_id', true));

CREATE POLICY "quiz_attempt_events_review_select" ON "quiz_attempt_events"
  FOR SELECT
  USING (can_review_course(quiz_attempt_course_id("attempt_id"), current_setting('app.current_user_id', true)));

CREATE POLICY "quiz_attempt_events_tenant_select" ON "quiz_attempt_events"
  FOR SELECT
  USING (quiz_belongs_to_organization(quiz_attempt_quiz_id("attempt_id"), current_setting('app.current_organization_id', true)));

CREATE POLICY "quiz_attempt_events_platform_select" ON "quiz_attempt_events"
  FOR SELECT
  USING (is_platform_owner(current_setting('app.current_user_id', true)));

-- 180-day retention (Phase 4 §D.5): the sweep deletes with no context and
-- this policy is what independently bounds what it may delete.
CREATE POLICY "quiz_attempt_events_retention_delete" ON "quiz_attempt_events"
  FOR DELETE
  USING ("server_at" < now() - interval '180 days');

-- quiz_results ------------------------------------------------------------
ALTER TABLE "quiz_results" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "quiz_results" FORCE ROW LEVEL SECURITY;

CREATE POLICY "quiz_results_self_select" ON "quiz_results"
  FOR SELECT
  USING ("student_id" = current_setting('app.current_user_id', true));

CREATE POLICY "quiz_results_self_insert" ON "quiz_results"
  FOR INSERT
  WITH CHECK ("student_id" = current_setting('app.current_user_id', true));

CREATE POLICY "quiz_results_self_update" ON "quiz_results"
  FOR UPDATE
  USING ("student_id" = current_setting('app.current_user_id', true))
  WITH CHECK ("student_id" = current_setting('app.current_user_id', true));

CREATE POLICY "quiz_results_review_select" ON "quiz_results"
  FOR SELECT
  USING (can_review_course(quiz_course_id("quiz_id"), current_setting('app.current_user_id', true)));

CREATE POLICY "quiz_results_review_insert" ON "quiz_results"
  FOR INSERT
  WITH CHECK (can_review_course(quiz_course_id("quiz_id"), current_setting('app.current_user_id', true)));

CREATE POLICY "quiz_results_review_update" ON "quiz_results"
  FOR UPDATE
  USING (can_review_course(quiz_course_id("quiz_id"), current_setting('app.current_user_id', true)))
  WITH CHECK (can_review_course(quiz_course_id("quiz_id"), current_setting('app.current_user_id', true)));

CREATE POLICY "quiz_results_tenant_select" ON "quiz_results"
  FOR SELECT
  USING (quiz_belongs_to_organization("quiz_id", current_setting('app.current_organization_id', true)));

CREATE POLICY "quiz_results_platform_select" ON "quiz_results"
  FOR SELECT
  USING (is_platform_owner(current_setting('app.current_user_id', true)));

-- quiz_student_overrides --------------------------------------------------
ALTER TABLE "quiz_student_overrides" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "quiz_student_overrides" FORCE ROW LEVEL SECURITY;

CREATE POLICY "quiz_student_overrides_self_select" ON "quiz_student_overrides"
  FOR SELECT
  USING ("student_id" = current_setting('app.current_user_id', true));

CREATE POLICY "quiz_student_overrides_review_all" ON "quiz_student_overrides"
  FOR ALL
  USING (can_review_course(quiz_course_id("quiz_id"), current_setting('app.current_user_id', true)))
  WITH CHECK (can_review_course(quiz_course_id("quiz_id"), current_setting('app.current_user_id', true)));

CREATE POLICY "quiz_student_overrides_tenant_select" ON "quiz_student_overrides"
  FOR SELECT
  USING (quiz_belongs_to_organization("quiz_id", current_setting('app.current_organization_id', true)));

CREATE POLICY "quiz_student_overrides_platform_select" ON "quiz_student_overrides"
  FOR SELECT
  USING (is_platform_owner(current_setting('app.current_user_id', true)));

-- quiz_attempts: reviewers may now WRITE (manual grading, void). Phase 1
-- gave them SELECT only.
CREATE POLICY "quiz_attempts_review_update" ON "quiz_attempts"
  FOR UPDATE
  USING (can_review_course(quiz_course_id("quiz_id"), current_setting('app.current_user_id', true)))
  WITH CHECK (can_review_course(quiz_course_id("quiz_id"), current_setting('app.current_user_id', true)));

-- certificate_templates ---------------------------------------------------
ALTER TABLE "certificate_templates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "certificate_templates" FORCE ROW LEVEL SECURITY;

CREATE POLICY "certificate_templates_tenant_select" ON "certificate_templates"
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM "academies" a
      WHERE a."id" = "certificate_templates"."academy_id"
        AND a."organization_id"::text = current_setting('app.current_organization_id', true)
    )
  );

CREATE POLICY "certificate_templates_tenant_write" ON "certificate_templates"
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM "academies" a
      WHERE a."id" = "certificate_templates"."academy_id"
        AND a."organization_id"::text = current_setting('app.current_organization_id', true)
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM "academies" a
      WHERE a."id" = "certificate_templates"."academy_id"
        AND a."organization_id"::text = current_setting('app.current_organization_id', true)
    )
  );

CREATE POLICY "certificate_templates_platform_select" ON "certificate_templates"
  FOR SELECT
  USING (is_platform_owner(current_setting('app.current_user_id', true)));

-- certificates --------------------------------------------------------------
ALTER TABLE "certificates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "certificates" FORCE ROW LEVEL SECURITY;

CREATE POLICY "certificates_self_select" ON "certificates"
  FOR SELECT
  USING ("student_id" = current_setting('app.current_user_id', true));

CREATE POLICY "certificates_review_select" ON "certificates"
  FOR SELECT
  USING (can_review_course("course_id", current_setting('app.current_user_id', true)));

CREATE POLICY "certificates_tenant_select" ON "certificates"
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM "academies" a
      WHERE a."id" = "certificates"."academy_id"
        AND a."organization_id"::text = current_setting('app.current_organization_id', true)
    )
  );

CREATE POLICY "certificates_tenant_insert" ON "certificates"
  FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM "academies" a
      WHERE a."id" = "certificates"."academy_id"
        AND a."organization_id"::text = current_setting('app.current_organization_id', true)
    )
  );

CREATE POLICY "certificates_tenant_update" ON "certificates"
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM "academies" a
      WHERE a."id" = "certificates"."academy_id"
        AND a."organization_id"::text = current_setting('app.current_organization_id', true)
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM "academies" a
      WHERE a."id" = "certificates"."academy_id"
        AND a."organization_id"::text = current_setting('app.current_organization_id', true)
    )
  );

CREATE POLICY "certificates_platform_select" ON "certificates"
  FOR SELECT
  USING (is_platform_owner(current_setting('app.current_user_id', true)));

-- certificate_serial_counters: readable in tenant context, written ONLY by
-- `next_certificate_serial` (definer) — no write policy on purpose.
ALTER TABLE "certificate_serial_counters" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "certificate_serial_counters" FORCE ROW LEVEL SECURITY;

CREATE POLICY "certificate_serial_counters_tenant_select" ON "certificate_serial_counters"
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM "academies" a
      WHERE a."id" = "certificate_serial_counters"."academy_id"
        AND a."organization_id"::text = current_setting('app.current_organization_id', true)
    )
  );

-- course_progress: certificate issuance runs in the academy's tenant
-- context (never as the learner — a learner must not be the principal
-- that writes their own certificate state), so the tenant tier gains
-- UPDATE. Scope identical to the existing tenant SELECT.
CREATE POLICY "course_progress_tenant_update" ON "course_progress"
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM "enrollments" e
      JOIN "academies" a ON a."id" = e."academy_id"
      WHERE e."id" = "course_progress"."enrollment_id"
        AND a."organization_id"::text = current_setting('app.current_organization_id', true)
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM "enrollments" e
      JOIN "academies" a ON a."id" = e."academy_id"
      WHERE e."id" = "course_progress"."enrollment_id"
        AND a."organization_id"::text = current_setting('app.current_organization_id', true)
    )
  );
