/**
 * Theme 1 plan §D.2 — starter-content provenance: generation records which
 * template (and version) first generated a website, once, and never
 * overwrites it.
 */
import type { Prisma } from '@prisma/client';
import { WebsiteBootstrapService } from './website-bootstrap.service';
import { WebsiteGenerationService } from './website-generation.service';

type Row = Record<string, unknown>;
const tx = {} as Prisma.TransactionClient;
const ACADEMY = { id: 'a1', name: 'Horizon', description: null };

function setup(initialConfiguration: Row | null = null, existingPages: Row[] = []) {
  let configuration = initialConfiguration;
  const pages = [...existingPages];
  const configurationRepository = {
    findByAcademyId: async () => configuration,
    create: async (_tx: unknown, data: Row) => {
      const rest = { ...data };
      delete rest.academy;
      configuration = {
        ...rest,
        academyId: ACADEMY.id,
        templateKey: null,
        templateVersion: null,
      };
      return configuration;
    },
    update: async (_tx: unknown, _id: string, data: Row) => {
      configuration = { ...configuration!, ...data };
      return configuration;
    },
  };
  const pagesRepository = {
    findCoreByType: async (_tx: unknown, _a: string, coreType: string) =>
      pages.find((page) => page.coreType === coreType) ?? null,
    findById: async (_tx: unknown, _a: string, id: string) =>
      pages.find((page) => page.id === id) ?? null,
    create: async (_tx: unknown, data: Row) => {
      const page = { ...data, id: `p${pages.length + 1}` };
      pages.push(page);
      return page;
    },
    update: async () => undefined,
  };
  const bootstrap = new WebsiteBootstrapService(
    configurationRepository as never,
    pagesRepository as never,
  );
  const service = new WebsiteGenerationService(
    { findById: async () => ACADEMY } as never,
    configurationRepository as never,
    pagesRepository as never,
    bootstrap,
  );
  return { service, read: () => configuration };
}

describe('website generation — template provenance', () => {
  it('records the template and version on first generation', async () => {
    const { service, read } = setup();
    await service.generate(tx, ACADEMY.id, 'modern-education', 'complete');
    expect(read()).toMatchObject({ templateKey: 'modern-education', templateVersion: 1 });
  });

  it('never rewrites it: a retry, or a later generation for another theme, keeps the first', async () => {
    const { service, read } = setup();
    await service.generate(tx, ACADEMY.id, 'modern-education', 'complete');
    await service.generate(tx, ACADEMY.id, 'modern-education', 'complete');
    await service.generate(tx, ACADEMY.id, 'bold-creative', 'complete');
    expect(read()).toMatchObject({ templateKey: 'modern-education', templateVersion: 1 });
  });

  it('records nothing when every page already existed (not generated by a template)', async () => {
    const existing = ['home', 'about', 'courses', 'faqs', 'contact'].map(
      (coreType, index) => ({
        id: `old${index}`,
        coreType,
      }),
    );
    const { service, read } = setup(null, existing);
    await service.generate(tx, ACADEMY.id, 'premium-academy', 'complete');
    expect(read()).toMatchObject({ templateKey: null, templateVersion: null });
  });
});
